name: 'Moose CI'
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v4
            - uses:  moosetechnology/setup-MooseCI@main
              with:
                project-path: tslearn
                report-path: .moose-ci/report
            - uses: actions/download-artifact@v4
              with:
                name: moose-ci-report
            - name: 'Check report exists'
              working-directory: .
              run: test -f .moose-ci/report/report*.json