name: 'Moose CI'
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4
            - uses:  moosetechnology/setup-MooseCI@main
              with:
                project-path: tslearn
            - uses: actions/download-artifact@v4
              with:
                name: moose-ci-report
            - name: 'Check report exists'
              working-directory: .
              run: test -f tslearn/.moose-ci/report/report*.json